version: '3'
services:
  app:
    build: .
    image: img-app-minhas-series:latest
    environment:
      NODE_ENV: development
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - "$PWD/apps/mongo:/data/db" #diretório onde ficarão salvas os meus documentos 
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"



